### ISSUE TITLE
Binary hoi crash

### ISSUE THREAD

**Issue by botka4aet** [samirelanduk/hoi4.py#1]
With Python 3.8.2
> python -m hoi4 binary2plain -i iraq.hoi4 -o 1_converted_save_file.hoi4

```
Traceback (most recent call last):
  File "*\Python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "*\Python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "*\Python38-32\lib\site-packages\hoi4\__main__.py", line 13, in <module>
    text = load_as_text(args.input)
  File "*\Python38-32\lib\site-packages\hoi4\parse.py", line 13, in load_as_text
    return parse_binary_hoi4(f)
  File "*\Python38-32\lib\site-packages\hoi4\binary.py", line 17, in parse_binary_hoi4
    return decorate(raw_filestring)
  File "*\Python38-32\lib\site-packages\hoi4\binary.py", line 65, in decorate
    date = f'"{create_date(m[2])}"'
  File "*\Python38-32\lib\site-packages\hoi4\binary.py", line 95, in create_date
    datestring = datetime.strftime(dt, "%Y.%-m.%-d.%-H")
ValueError: Invalid format string
```

**Comment by samirelanduk** [comment]
Hmm - would need to see the save file to be able to diagnose this. Depending on its size, is it something you could attach?
